name: Bump Dependencies

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Update Dependencies
        run: bun update

      - name: Commit and Push Changes
        env:
          USERNAME_GITEA: ${{ secrets.USERNAME_GITEA }}
          TOKEN_GITEA: ${{ secrets.TOKEN_GITEA }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
        run: |
          git config --global user.name "LibreCloud Actions Bot"
          git config --global user.email "git@pontusmail.org"
          echo "Connecting to $SERVER_URL"
          git remote set-url origin https://${USERNAME_GITEA}:${TOKEN_GITEA}@git.pontusmail.org/aidan/request-bot.git
          git add .
          git commit -m "chore: bump dependencies" || exit 0
          git push origin main